
- name: Run ad-hoc commands
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
      - name: run show version on remote devices
        bigip_command:
            commands:
              - run /cm config-sync to-group run /cm config-sync to-group device-group-failover-71da91c91c55
            server: 192.168.2.101
            password: admin
            user: admin
            validate_certs: no
        register: print_output
        delegate_to: localhost
      - debug: var=print_output.stdout_lines
