
- name: Run ad-hoc commands
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
      - name: run show version on remote devices
        bigip_command:
            commands:
              - show sys version
              - list ltm virtual
            wait_for:
              - result[0] contains BIG-IP
              - result[1] contains my-vs
            server: 192.168.2.101
            password: admin
            user: admin
            validate_certs: no
        register: result
        delegate_to: localhost
