
- name: Run ad-hoc commands
  hosts: 192.168.2.101
  connection: ssh
  
  tasks:
  
      - name: run show version on remote devices
        bigip_command:
            commands:
              - show sys version | grep Version
        #    wait_for:
        #      - result[0] contains Version
            server: 192.168.2.101
       #     password: admin
             user: root
            validate_certs: no
        register: print_output
        delegate_to: localhost
      - debug: var=print_output.stdout_lines
