
- name: Run ad-hoc commands
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
      - name: run show version on remote devices
        bigip_command:
            commands: show sys version
            server: 192.168.2.101
            password: admin
            user: admin
            validate_certs: no
        delegate_to: localhost
