- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local

  tasks:
  
      - name: Collect BIG-IP facts
        bigip_facts:
            server: 192.168.2.101
            user: admin
            password: admin
            include: device,device_group,system_info
            validate_certs: no
        delegate_to: localhost
        
      - name: display bigip facts output
        debug:
          msg:
           - "Hostname: {{ system_info.system_information.host_name }}"
           - "Mgmt IP: {{ device['/Common/' + system_info.system_information.host_name].management_address }}"
           - "SW Version: {{ system_info.product_information.product_version }}"
           - "Status: {{ device['/Common/' + system_info.system_information.host_name].failover_state }}"
        
        
     #   register: print_output
     # - debug: var=print_output.stdout_lines
