- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local

  tasks:
  
      - name: Collect BIG-IP facts
        bigip_facts:
            server: 192.168.2.101
            user: admin
            password: admin
            include: device,device_group,system_info
            validate_certs: no
        delegate_to: localhost
     #   register: print_output
     # - debug: var=print_output.stdout_lines
