
- name: Perform HA config-sync
  hosts: 192.168.2.101
  connection: local
  
  tasks:
      - name: Sync config
        bigip_configsync_action:
            device_group: device-group-failover-71da91c91c55
            sync_device_to_group: yes
            server: 192.168.2.101
            user: admin
            password: admin
            validate_certs: no
        delegate_to: localhost
