---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  gather_facts: false
  
- name: Check sync status
  bigip_command:
    server: 192.168.2.101
    user: "admin"
    password: "admin"
    commands:
     - show cm sync-status
    wait_for:
     - result[0] contains "green"
    match: all
   delegate_to: localhost
