
- name: Perform HA config-sync
  hosts: 192.168.2.101
  connection: ssh
  
  tasks:
      - name: Sync config
        bigip_configsync_action:
            device_group: device-group-failover-71da91c91c55
            sync_device_to_group: yes
            server: 192.168.2.101
            user: root
            password: default
            validate_certs: no
        delegate_to: localhost
