---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  gather_facts: false
  
  tasks:
  - name: Sync configuration from device to group
    bigip_configsync_action:
     server: 192.168.2.101
     device_group: HA_Group
     sync_device_to_group: yes
     user: admin
     password: admin
     validate_certs: no
    delegate_to: localhost
