---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
      - name: Create node20
        bigip_node:
            host: 10.10.10.17
            name: node-20
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost

      - name: Add nodes to pool
        bigip_pool_member:
            description: webserver-1
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: admin
            pool: web
            port: 80
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost
        with_items:
            - host: 10.10.10.17
              name: node-20
