---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: ratio-member
         name: mypool
         password: admin
         server: 192.168.2.101
         slow_ramp_time: 120
         user: admin
         validate_certs: no
     delegate_to: localhost
