- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local

  
  tasks:
      - name: Create node
        bigip_node:
            host: 173.20.30.46
            name: ProdNode3
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost
            
      - name: Create node
        bigip_node:
            host: 173.20.30.50
            name: ProdNode33
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost     
            
       - name: Create node
        bigip_node:
            host: 173.20.30.51
            name: ProdNode34
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost           
   
            
      - name: Create pool
        bigip_pool:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             name: ProdPool2
             partition: Common
             lb_method: round-robin
             monitor_type: and_list
             monitors:
               - http
        delegate_to: localhost
 
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: 173.20.30.46
             name: ProdNode3
             password: admin
             pool: ProdPool2
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: 173.20.30.50
             name: ProdNode33
             password: admin
             pool: ProdPool2
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        
        
        - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: 173.20.30.51
             name: ProdNode34
             password: admin
             pool: ProdPool2
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        
      - name: Create a VIP
        bigip_virtual_server:
            description: VIP for pool
            destination: 210.16.48.32
            password: admin
            name: ProdVIP
            pool: ProdPool2
            port: 443
            server: 192.168.2.101
            snat: Automap
            user: admin
            all_profiles:
                 - http
                 - clientssl
            validate_certs: no
        delegate_to: localhost
