---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
       
      - name: Add pool member
        bigip_pool_member:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             pool: this_awesome_pool2
             partition: Common
             host: "{{ ansible_default_ipv4['address'] }}"
             port: 443
        delegate_to: localhost
