---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
      - name: Create node20
        bigip_node:
            host: 10.10.10.124
            name: node-266
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost
