---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  vars:
    host: 10.20.30.40
    name: node-99
    poolname: view_pool
    vipip: 172.16.20.50
  
  tasks:
      - name: Create node
        bigip_node:
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost
                    
      - name: Create pool
        bigip_pool:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             name: "{{ item.poolname }}"
             partition: Common
             lb_method: round-robin
             monitor_type: and_list
             monitors:
               - http
        delegate_to: localhost
 
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: "{{ item.host }}"
             name: node-new
             password: admin
             pool: "{{ item.poolname }}"
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        
      - name: Create a VIP
        bigip_virtual_server:
            description: VIP for pool
            destination: "{{ item.vipip }}"
            password: admin
            name: New_VIP_1
            pool: "{{ item.poolname }}"
            port: 443
            server: 192.168.2.101
            snat: Automap
            user: admin
            all_profiles:
                 - http
                 - clientssl
            validate_certs: no
        delegate_to: localhost
