---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
      - name: Create pool
        bigip_pool:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             name: this_awesome_pool2
             partition: Common
             lb_method: round-robin
             monitor_type: and_list
             monitors:
               - http
        delegate_to: localhost
 
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: 10.10.10.125
             name: node-267
             password: admin
             pool: this_awesome_pool2
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
