---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
      - name: Create node
        bigip_node:
            host: "{{ item.host }}"
            name: "{{ item.nodename }}"
            password: admin
            server: 192.168.2.101
            user: admin
            validate_certs: no
        delegate_to: localhost
        with_items:
            - host: 29.37.28.38
            - nodename: ProdNode_101
                    
      - name: Create pool
        bigip_pool:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             name: "{{ item.poolname }}"
             partition: Common
             lb_method: round-robin
             monitor_type: and_list
             monitors:
               - http
        delegate_to: localhost
        with_items:
            - poolname: ProdPool_101
 
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: "{{ item.nodename }}"
             name: node-new
             password: admin
             pool: "{{ item.poolname }}"
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        with_items:
            - nodename: ProdNode_101
            - poolname: ProdPool_101
        
      - name: Create a VIP
        bigip_virtual_server:
            description: VIP for pool
            destination: "{{ item.vipip }}"
            password: admin
            name: New_VIP_1
            pool: "{{ item.poolname }}"
            port: 443
            server: 192.168.2.101
            snat: Automap
            user: admin
            all_profiles:
                 - http
                 - clientssl
            validate_certs: no
        delegate_to: localhost
        with_items:
            - vipip: 217.16.87.202
            - poolname: ProdPool_101
