---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
      - name: Create node1
        bigip_node:
            host: 10.10.10.10
            name: node-1
            password: default
            server: 192.168.2.101
            user: root
            validate_certs: no
        delegate_to: localhost
