---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
  
      - name: Create pool
        bigip_pool:
             server: 192.168.2.101
             user: admin
             password: admin
             state: present
             name: this_awesome_pool_0
             partition: Common
             lb_method: round-robin
             monitor_type: and_list
             monitors:
               - http
        delegate_to: localhost
 
      - name: Add pool member
        bigip_pool_member:
             description: webserver-1
             host: 10.10.10.10
             name: node-1
             password: admin
             pool: this_awesome_pool_0
             port: 80
             server: 192.168.2.101
             user: admin
             validate_certs: no
        delegate_to: localhost
        
        - name: Create a VIP
          bigip_virtual_server:
              description: VIP for pool
              destination: 170.10.213.76
              password: admin
              name: New_VIP_1
              pool: this_awesome_pool_0
              port: 443
              server: 192.168.2.101
              snat: Automap
              user: admin
              all_profiles:
                   - http
                   - clientssl
              validate_certs: no
           delegate_to: localhost
