---
- name: Create a VIP, pool, pool members, and nodes
  hosts: 192.168.2.101
  connection: local
  
  tasks:
   
     - name: Create pool
       bigip_pool:
            server: 192.168.2.101
            user: admin
            password: admin
            state: present
            name: monitored_pool
            partition: Common
            lb_method: round-robin
            monitors:
              - tcp
       delegate_to: localhost
